/* eslint-disable react/no-unescaped-entities */
import type { Metadata } from "next";
import Header  from "./components/header/header"
import Footer from './components/footer/footer'

import styles from './page.module.scss'
import './globalStyles/globalThemes.css'

export const metadata: Metadata = {
  title: "Mikkel's Logbook",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body>
        <div className={styles.container}>
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
};
