/* eslint-disable react/no-unescaped-entities */
import type { Metadata } from "next";
import { header }  from "./components/header/header"
import { footer } from './components/footer/footer'
import Link from "next/link";

import styles from './page.module.scss'

export const metadata: Metadata = {
  title: "Mikkel's Logbook",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const header = (
    <header>
            <div className={styles.header}>
              <Link className={styles.title} href="/">
                <h1>Mikkel's Logbook</h1>
              </Link>
                <p>Welcome to my logbook</p>
            </div>
        </header>
  )

  const footer = (
    <footer>
            <div className={styles.footer}>
                <p>Made by Mikkel W.</p>
            </div>
        </footer>
  )
  
  return (
    <html lang="en">
      <body>
        <div className={styles.container}>
        {header}
        {children}
        {footer}
        </div>
      </body>
    </html>
  );
};
